language: node_js
node_js:
  - "node"
  cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: public # Directory to push to GitHub Pages
  on:
    branch: master